name: mochilapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  http: ^0.13.3
  system_info: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0 

flutter_icons:
  android: 'ic_launcher'
  ios: true
  image_path: "assets/icon/ic_launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  uses-material-design: true
  assets:
    - assets/svg/facebookWhite.svg
    - assets/svg/facebook.svg
    - assets/svg/google.svg
    - assets/svg/tent.svg
    - assets/svg/tentDark.svg
    
  fonts:
    - family: MulishBlack
      fonts:
         - asset: fonts/Mulish-Black.ttf

    - family: MulishBlackItalic
      fonts:
         - asset: fonts/Mulish-BlackItalic.ttf

    - family: MulishBold
      fonts:
         - asset: fonts/Mulish-Bold.ttf

    - family: MulishBoldItalic
      fonts:
         - asset: fonts/Mulish-BoldItalic.ttf

    - family: MulishExtraBold
      fonts:
         - asset: fonts/Mulish-ExtraBold.ttf

    - family: MulishExtraBoldItalic
      fonts:
         - asset: fonts/Mulish-ExtraBoldItalic.ttf

    - family: MulishExtraLight
      fonts:
         - asset: fonts/Mulish-ExtraLight.ttf

    - family: MulishExtraLightItalic
      fonts:
         - asset: fonts/Mulish-ExtraLightItalic.ttf

    - family: MulishItalic
      fonts:
         - asset: fonts/Mulish-Italic.ttf

    - family: MulishLight
      fonts:
         - asset: fonts/Mulish-Light.ttf

    - family: MulishLightItalic
      fonts:
         - asset: fonts/Mulish-LightItalic.ttf

    - family: MulishMedium
      fonts:
         - asset: fonts/Mulish-Medium.ttf

    - family: MulishMediumItalic
      fonts:
         - asset: fonts/Mulish-MediumItalic.ttf

    - family: MulishRegular
      fonts:
         - asset: fonts/Mulish-Regular.ttf

    - family: MulishSemiBold
      fonts:
         - asset: fonts/Mulish-SemiBold.ttf

    - family: MulishSemiBoldItalic
      fonts:
         - asset: fonts/Mulish-SemiBoldItalic.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
